# Generated by Django 2.1.7 on 2020-01-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20200101_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedroles',
            name='player_first',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selectedroles',
            name='player_last',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
